package TasteProfile;


/**
* TasteProfile/Song.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* Saturday, 7 October, 2017 5:53:34 PM CEST
*/

public abstract class Song implements org.omg.CORBA.portable.StreamableValue
{
  public String songId = null;
  public int playCount = (int)0;

  private static String[] _truncatable_ids = {
    TasteProfile.SongHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.songId = istream.read_string ();
    this.playCount = istream.read_long ();
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_string (this.songId);
    ostream.write_long (this.playCount);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TasteProfile.SongHelper.type ();
  }
} // class Song
