package TasteProfile;


/**
* TasteProfile/UserProfile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* Saturday, 7 October, 2017 5:53:34 PM CEST
*/

public abstract class UserProfile implements org.omg.CORBA.portable.StreamableValue
{
  public String userId = null;
  public TasteProfile.SongSequence songs = null;

  private static String[] _truncatable_ids = {
    TasteProfile.UserProfileHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.userId = istream.read_string ();
    this.songs = TasteProfile.SongSequenceHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_string (this.userId);
    TasteProfile.SongSequenceHelper.write (ostream, this.songs);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TasteProfile.UserProfileHelper.type ();
  }
} // class UserProfile
