package TasteProfile;

/**
* TasteProfile/UserProfileSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* Saturday, 7 October, 2017 5:53:34 PM CEST
*/

public final class UserProfileSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public TasteProfile.UserProfileSequence value = null;

  public UserProfileSequenceHolder ()
  {
  }

  public UserProfileSequenceHolder (TasteProfile.UserProfileSequence initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TasteProfile.UserProfileSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TasteProfile.UserProfileSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TasteProfile.UserProfileSequenceHelper.type ();
  }

}
